# docker-compose.yml
version: "3.8"

services:
  api-node-one:
    image: api-node-one:latest # 确保这个标签和 deploy.yml 中构建的标签一致
    container_name: api-node-one_container
    ports:
      - "3000:3000" # 将宿主机的 80 端口映射到容器的 3000 端口
    restart: always # 容器退出后自动重启
    volumes:
      - ./logs:/app/logs # 将宿主机 docker-compose.yml 所在目录下的 logs 文件夹映射到容器的 /app/logs
    environment:
      # 如果有 .env 文件，推荐使用 env_file
      # env_file:
      #   - ./.env
      # 或者直接在这里定义环境变量
      # - NODE_ENV=production # 如果你只有一个环境，可以考虑移除这个或设置为其他值
