# .github/workflows/deploy.yml
name: 部署 Node.js 应用到服务器 # 工作流名称

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: 检出代码 # 步骤名称
        uses: actions/checkout@v4

      - name: 设置 Docker BuildX # 步骤名称
        uses: docker/setup-buildx-action@v3

      - name: 本地构建并加载 Docker 镜像 # 步骤名称
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: api-node-one:latest

      - name: 停止并移除旧容器 # 步骤名称
        run: |
          docker-compose down api-node-one || true

      - name: 使用 Docker Compose 部署 # 步骤名称
        run: |
          docker-compose up -d api-node-one

      - name: 清理旧 Docker 镜像 # 步骤名称
        run: docker image prune -f
